### ISSUE TITLE
Preparing bdpar for new rtweet release

### ISSUE THREAD

**Issue by llrs** [miferreiro/bdpar#1]
Dear Miguel,

I'm writing to you as the maintainer of bdpar because as the maintainer of rtweet I made some breaking changes on the future rtweet release 1.0.0.

While checking rtweet reverse dependencies I noticed you depend on rtweet::emojis which will be removed from the package (as well as with all the other data that was shipped with the package). 
Possible solutions are save the data from rtweet to your package and provide it in bdpar or use other data or packages containing emoji data. 
I am planning to submit the new rtweet 1.0.0 to CRAN in 2 months, I hope it is enough time to prepare bdpar for this change.

I would also like to encourage you to test rtweet 1.0.0 and report any bugs that might affect you. 
You'll notice that there have been several changes which might affect users of bdpar in ways I might have not detected. 
I'll try to fix all the bugs reported this first month on the last month before the submission to CRAN. 

Best, 

Lluís

**Comment by miferreiro** [comment]
Hi LLuís,

First of all, thank you for contacting me to notice this breaking changes on the future rtweet release 1.0.0.

Taking into account what you have explained, I have already updated the bdpar package to CRAN for removing the dependency with the emojis provided by the rtweet package.

I will keep an eye out for updates on the rtweet package to make sure that any changes do not affect the functioning of bdpar.

Best regards,

Miguel

**Comment by llrs** [comment]
Hi Miguel,

That was quick! Awesome!
I'm closing the issue as I don't expect to make further breaking changes before this release. 
However, I will send an email with more information to all rtweet dependencies with the futures events that might impact rtweet.
